name: C++
on:
  push:
  pull_request:
jobs:
  windows-latest:
    runs-on: 'windows-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Get GoogleTest
      run: git submodule update --init
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2      
    - name: Build tests
      run: msbuild CPP/Tests/VisualStudio/Tests_cpp.sln /p:Configuration=Release /p:Platform=x64
    - name: Run tests
      run: x64\Release\Tests.exe
      working-directory: CPP/Tests/VisualStudio
    - name: Build console demo program
      run: msbuild CPP/Examples/ConsoleDemo1/ConsoleDemo1_cpp.sln
